"""
LLM Router Benchmark Configuration.
IMPORTANT NOTICE:
All scores below are prototype reference benchmark scores compiled from published
evaluation summaries (e.g. HumanEval, GSM8K, ARC-Challenge, MMLU).
They are NOT locally measured or generated by our system.
This file serves as a configurable lookup table that can easily be updated or
replaced with live empirical measurements in the future.
"""
from typing import Dict
# Metadata describing reference data provenance
SCORE_SOURCE = "Public benchmark reference data (published evaluation summaries)"
SCORE_DATE = "2025-05-01"
SCORE_NOTE = "Prototype/reference benchmark scores — not locally measured benchmark results."
# Default fallback model when no specific model can be chosen
DEFAULT_MODEL = "qwen3:4b"
# Local models supported by the router
AVAILABLE_MODELS = [
    "qwen3:4b",
    "gemma3:4b",
    "qwen2.5-coder:3b",
]
# Models with native vision/multimodal capabilities
VISION_MODELS = [
    "gemma3:4b",
]
# Configurable prototype reference benchmark scores normalized to [0.0, 1.0]
BENCHMARK_SCORES: Dict[str, Dict[str, float]] = {
    "coding": {
        "qwen2.5-coder:3b": 0.84,
        "qwen3:4b": 0.70,
        "gemma3:4b": 0.62,
    },
    "math": {
        "qwen3:4b": 0.77,
        "gemma3:4b": 0.69,
        "qwen2.5-coder:3b": 0.58,
    },
    "reasoning": {
        "qwen3:4b": 0.81,
        "gemma3:4b": 0.73,
        "qwen2.5-coder:3b": 0.64,
    },
    "QA": {
        "qwen3:4b": 0.79,
        "gemma3:4b": 0.76,
        "qwen2.5-coder:3b": 0.63,
    
    },
}
# Standard dimension priority weights when multiple benchmark requirements are detected
# Notice: Complexity does NOT contribute a numerical score. Only benchmark dimensions are weighted.
DIMENSION_WEIGHT_PRIORITY = {
    "coding": 0.70,
    "math": 0.65,
    "reasoning": 0.35,
    "QA": 0.30,
    "general": 0.20,
}

